name: 2. SAST - Semgrep Scan

on:
  push:
    branches: [ "main", "master" ]

jobs:
  semgrep-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        uses: semgrep/semgrep-action@v1
        with:
          config: auto