name: 2. SAST - Semgrep Scan

on:
  push:
    branches: [ "main", "master" ]

jobs:
  semgrep-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Semgrep Scan
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep scan --config p/default /src
        continue-on-error: true